import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  // supabase/functions/** is Deno, not part of the app tsconfig — linted by
  // `deno lint` / `deno check`, not this config.
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'supabase/.temp',
      'supabase/functions',
      // git worktrees a subagent may have checked out — a separate checkout,
      // linted on its own branch, not part of this one.
      '.claude',
      // Generated by `npm run db:types` — not hand-maintained.
      'src/types/database.ts',
      // Local-only real-browser test harness + Playwright specs. Not part of
      // the app tsconfig; run via `npm run test:e2e`, formatted by Prettier.
      'e2e',
    ],
  },
  {
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-confusing-void-expression': [
        'error',
        { ignoreArrowShorthand: true },
      ],
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true },
      ],
    },
  },
  {
    // Test files and the shared test harness under src/test/** both stub
    // browser globals / prototype methods, which needs the same relaxations.
    files: ['**/*.test.{ts,tsx}', 'vitest.setup.ts', 'src/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
    },
  },
  {
    files: ['**/*.{js,cjs,mjs}', 'vite.config.ts'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  prettier,
);
